export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE";

export const GET_SIGNUP_REQUEST = "GET_SIGNUP_REQUEST";
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_FAILURE = "GET_SIGNUP_FAILURE";

//---------------------  Userdata  ---------------------- // 


export const USER_DATA_REQUEST =  "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS =  "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE =  "USER_DATA_FAILURE ";


export const EDIT_DATA_REQUEST = "EDIT_DATA_REQUEST";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
export const EDIT_DATA_FAILURE = "EDIT_DATA_FAILURE";

export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAILURE = "DELETE_DATA_FAILURE";


export const GETSINGLE_USER_REQUEST = "GETSINGLE_USER_REQUEST";
export const GETSINGLE_USER_SUCCESS = "GETSINGLE_USER_SUCCESS";
export const GETSINGLE_USER_FAILURE = "GETSINGLE_USER_FAILURE";


